#include <iostream>

#include "Problems.h"

// PROBLEM:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

static size_t SumEvenFib(int limit)
{
    int a = 1;
    int b = 2;
    size_t sum = b;

    for(;;)
    {
        int fib = a + b;
        a = b;
        b = fib;
        if (b > limit)
            break;

        if (0 == (b & 1))
        {
            sum += b;
        }
    }

    return sum;
}

void CProblem<2>::Execute()
{
    std::cout << "Problem 2 Solution: " << SumEvenFib(4000000) << std::endl;
}